// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbY6XypgAqE3xNe1PAl5Mqx9dKHkXIXHE',
    appId: '1:262644538458:web:a018ac90e20d5b04018c63',
    messagingSenderId: '262644538458',
    projectId: 'gentlecuts-e49a6',
    authDomain: 'gentlecuts-e49a6.firebaseapp.com',
    storageBucket: 'gentlecuts-e49a6.firebasestorage.app',
    measurementId: 'G-5RQQ28FM27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZykSQijpsFw2d39Oi4MZWsMf0VSu0z5Q',
    appId: '1:262644538458:android:d883468d1b5ddd77018c63',
    messagingSenderId: '262644538458',
    projectId: 'gentlecuts-e49a6',
    storageBucket: 'gentlecuts-e49a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbY6XypgAqE3xNe1PAl5Mqx9dKHkXIXHE',
    appId: '1:262644538458:web:2ef9bf7ec3a7df60018c63',
    messagingSenderId: '262644538458',
    projectId: 'gentlecuts-e49a6',
    authDomain: 'gentlecuts-e49a6.firebaseapp.com',
    storageBucket: 'gentlecuts-e49a6.firebasestorage.app',
    measurementId: 'G-8EK3Y6J09S',
  );
}
